//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.AcademicLoad = new HashSet<AcademicLoad>();
        }
    
        public int id_Department { get; set; }
        public int Number_Room { get; set; }
        public string Phone { get; set; }
        public int Quantity_Teachers { get; set; }
        public int id_Faculty { get; set; }
        public string Surname_Manager { get; set; }
        public string FName_Manager { get; set; }
        public string LName_Manager { get; set; }
        public string Name { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicLoad> AcademicLoad { get; set; }
    }
}
