//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id_Group { get; set; }
        public int Quantity_Students { get; set; }
        public int id_AcademicLoad { get; set; }
    
        public virtual AcademicLoad AcademicLoad { get; set; }
    }
}
