//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyYear()
        {
            this.AcademicLoad = new HashSet<AcademicLoad>();
        }
    
        public int id_StudyYear { get; set; }
        public int Start_Year { get; set; }
        public int End_Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicLoad> AcademicLoad { get; set; }
    }
}
